output.html: first.md second.md third.md
	pandoc first.md second.md third.md -s -o output.html


# ---------------------------------------
# Alternative version of pandoc command
# ---------------------------------------

#output.html: first.md second.md third.md
#	pandoc *.md -s -o output.html
